### ISSUE TITLE
can't set BootstrapEditText start text at top left

### ISSUE THREAD

**Issue by azizimusa** [Bearded-Hen/Android-Bootstrap#128] opened 2015-11-23 15:19 UTC
This is my BootstrapEditText in my layout 
````
<com.beardedhen.androidbootstrap.BootstrapEditText
                    xmlns:app="http://schemas.android.com/apk/res-auto"
                    android:layout_width="match_parent"
                    android:layout_height="130dp"
                    android:hint="@string/form_input"
                    android:layout_marginTop="10dp"
                    android:layout_marginBottom="10dp"
                    app:bootstrapSize="lg"
                    app:bootstrapBrand="info"
                    app:roundedCorners="true"
                    android:gravity="top|left"/>
````

I want it when the user start typing inside it. The text start at top and left corner. Seem that the gravity i set isn't work.

**Comment by SelimEmre** [comment] 2015-11-23 16:23
Please try BootstrapEdittext id .setGravity(Gravity.TOP);

**Comment by jamie-beardedhen** [comment] 2015-11-23 16:25
Duplicate of #115, code itself is fixed, the artefact hasn't been updated yet

**Closed by jamie-beardedhen** 2015-11-23 16:25 UTC
